name: CI/CD Deploy simplecrud          # Название пайплайна (отображается в GitHub Actions)

on:
  push:
    branches: [ "main" ]               # Запуск при пуше в ветку main

env:
  IMAGE_NAME: almuko/simplecrud        # Имя Docker-образа в Docker Hub

jobs:
  build-and-push:                      # Джоб: сборка и публикация образа
    runs-on: ubuntu-latest             # Запуск на GitHub-hosted runner (Ubuntu)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      # Забираем исходный код из репозитория

      - name: Log in to Docker Hub
        uses: docker/login-action@v2   # Авторизация в Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                        # Контекст сборки — текущая папка
          push: true                        # Публикуем образ в Docker Hub
          tags: |                           # Несколько тегов
            ${{ env.IMAGE_NAME }}:latest    # latest (для простоты)
            ${{ env.IMAGE_NAME }}:${{ github.sha }}  # тег по SHA коммита (уникальный)

  deploy:                                  # Джоб: деплой в Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push                  # Выполняется только после успешной сборки
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3          # Клонируем репозиторий (для доступа к манифестам)

      - name: Install kubectl
        uses: azure/setup-kubectl@v4       # Ставим kubectl
        with:
          version: latest

      - name: Setup Kubeconfig
        shell: bash
        run: |                             # Создаём kubeconfig из GitHub Secrets
          mkdir -p "$HOME/.kube"
          cat > "$HOME/.kube/config" <<'EOF'
          ${{ secrets.KUBECONFIG }}
          EOF

      - name: Update image tag in manifest
        run: |                             # Подставляем SHA в simplecrud.yaml
          sed -i "s|\${IMAGE_TAG}|${{ github.sha }}|g" k8s/simplecrud.yaml

      - name: Install cert-manager
        run: |                             # Устанавливаем cert-manager для TLS
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=180s

      - name: Deploy ClusterIssuer (Let's Encrypt)
        run: kubectl apply --validate=false -f k8s/cluster-issuer.yaml

      - name: Deploy Postgres (only if not exists)
        run: |                             # Проверяем, есть ли StatefulSet postgres
          if ! kubectl get statefulset postgres -n default >/dev/null 2>&1; then
            echo "Postgres not found. Creating..."
            kubectl apply -f k8s/postgres.yaml
            kubectl rollout status statefulset/postgres -n default --timeout=180s
          else
            echo "✅ Postgres already exists. Skipping creation."
          fi

      - name: Recreate simplecrud-db-secret
        run: |                             # Обновляем секрет с DATABASE_URL
          kubectl delete secret simplecrud-db-secret -n default --ignore-not-found
          kubectl create secret generic simplecrud-db-secret \
            --from-literal=DATABASE_URL='postgres://postgres:Zxcvbnm123@postgres:5432/simplecrud?sslmode=disable'

      - name: Cleanup old migration job and pods
        run: |                             # Чистим старый Job миграций и Pod'ы
          if kubectl get job simplecrud-migrate -n default >/dev/null 2>&1; then
            echo "🗑 Deleting old migration job..."
            kubectl delete job simplecrud-migrate -n default
          fi
          echo "🧹 Cleaning up old migration pods..."
          for pod in $(kubectl get pods -n default -l job-name=simplecrud-migrate -o jsonpath='{.items[*].metadata.name}'); do
            kubectl delete pod -n default $pod --ignore-not-found || true
          done

      - name: Run migrations Job
        run: |                             # Запускаем миграции
          kubectl apply -f k8s/migrate.yaml
          echo "⏳ Waiting for migrations to complete..."
          if ! kubectl wait --for=condition=complete job/simplecrud-migrate -n default --timeout=600s; then
            echo "❌ Migration job did not complete. Showing logs from all pods..."
            for pod in $(kubectl get pods -n default -l job-name=simplecrud-migrate -o jsonpath='{.items[*].metadata.name}'); do
              echo "🔹 Logs from pod: $pod"
              kubectl logs -n default $pod || true
              echo "--------------------------------------"
            done
            exit 1
          fi
          echo "✅ Migration job completed successfully."
          kubectl delete job simplecrud-migrate -n default --ignore-not-found

      - name: Deploy App (Deployment + Service + Ingress)
        run: kubectl apply -f k8s/simplecrud.yaml

      - name: Wait for app rollout
        run: kubectl rollout status deployment/simplecrud -n default --timeout=180s

      - name: Wait for TLS certificate
        run: |                             # Ждём выпуск TLS-сертификата
          echo "⏳ Waiting for TLS certificate simplecrud-tls..."
          kubectl wait --for=condition=Ready certificate/simplecrud-tls -n default --timeout=300s || \
            (echo "❌ TLS certificate was not issued" && kubectl describe certificate/simplecrud-tls -n default && exit 1)

      - name: Debug simplecrud pods if rollout fails
        if: failure()                      # Если деплой упал — выводим логи
        run: |
          kubectl get pods -n default
          for pod in $(kubectl get pods -n default -l app=simplecrud -o jsonpath='{.items[*].metadata.name}'); do
            echo "Logs from $pod"
            kubectl logs -n default $pod --tail=50 || true
            echo "---"
          done

      - name: Test API health endpoint
        run: |                             # Проверяем доступность API
          echo "🌍 Testing API endpoint..."
          curl -vk --retry 5 --retry-delay 10 https://simplecrud.compnet.kz/health | grep '"status":"ok"'

      - name: Show Ingress and endpoints
        run: |                             # Отладка: выводим ingress, сервисы, pod'ы
          kubectl get ingress -n default
          kubectl get svc -n default
          kubectl get pods -o wide -n default
