name: CI/CD Deploy simplecrud          # Название пайплайна (видно в GitHub Actions)

on:
  push:
    branches: [ "main" ]               # Триггер: запускать при пуше в ветку main

env:
  IMAGE_NAME: almuko/simplecrud        # Имя Docker-образа (в Docker Hub)

jobs:
  build-and-push:                      # Джоб: сборка и публикация Docker-образа
    runs-on: ubuntu-latest             # Виртуальная машина Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      # Забираем код из репозитория

      - name: Log in to Docker Hub
        uses: docker/login-action@v2   # Логинимся в Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Логин из GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}   # Пароль из GitHub Secrets

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4  # Сборка и публикация образа
        with:
          context: .                        # Контекст сборки — текущая папка
          push: true                        # Загружаем образ в Docker Hub
          tags: 
            ${{ env.IMAGE_NAME }}:latest    # Имя и тег образа (latest)

  deploy:                                  # Джоб: деплой в Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push                  # Зависимость: запуск только после сборки
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3          # Ещё раз клонируем репозиторий (нужны YAML манифесты)

      - name: Install kubectl
        uses: azure/setup-kubectl@v4       # Устанавливаем kubectl
        with:
          version: latest                  # Берём последнюю стабильную версию

      - name: Setup Kubeconfig
        shell: bash
        run: |                             # Настраиваем kubeconfig из GitHub Secrets
          mkdir -p "$HOME/.kube"
          cat > "$HOME/.kube/config" <<'EOF'
          ${{ secrets.KUBECONFIG }}
          EOF

      - name: Install cert-manager
        run: |                             # Устанавливаем cert-manager в кластер
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.yaml
          kubectl rollout status deployment/cert-manager -n cert-manager --timeout=180s      

      - name: Deploy ClusterIssuer (Let's Encrypt)
        run: kubectl apply --validate=false -f k8s/cluster-issuer.yaml
        # Подключаем ClusterIssuer для автоматического выпуска TLS сертификатов (Let's Encrypt)

      - name: Deploy Postgres (only if not exists)
        run: |                             # Поднимаем Postgres, если ещё не создан
          if ! kubectl get statefulset postgres -n default >/dev/null 2>&1; then
            echo "Postgres not found. Creating..."
            kubectl apply -f k8s/postgres.yaml
            kubectl rollout status statefulset/postgres -n default --timeout=180s
          else
            echo "✅ Postgres already exists. Skipping creation."
          fi

      - name: Recreate simplecrud-db-secret
        run: |                             # Обновляем секрет с DATABASE_URL
          kubectl delete secret simplecrud-db-secret -n default --ignore-not-found
          kubectl create secret generic simplecrud-db-secret \
            --from-literal=DATABASE_URL='postgres://postgres:Zxcvbnm123@postgres:5432/simplecrud?sslmode=disable'

      - name: Cleanup old migration job and pods
        run: |                             # Чистим старый Job для миграций и его Pod'ы
          if kubectl get job simplecrud-migrate -n default >/dev/null 2>&1; then
            echo "🗑 Deleting old migration job..."
            kubectl delete job simplecrud-migrate -n default
          fi
          echo "🧹 Cleaning up old migration pods..."
          for pod in $(kubectl get pods -n default -l job-name=simplecrud-migrate -o jsonpath='{.items[*].metadata.name}'); do
            kubectl delete pod -n default $pod --ignore-not-found || true
          done

      - name: Run migrations Job
        run: |                             # Запускаем Job для миграций
          kubectl apply -f k8s/migrate.yaml
          echo "⏳ Waiting for migrations to complete..."
          if ! kubectl wait --for=condition=complete job/simplecrud-migrate -n default --timeout=600s; then
            echo "❌ Migration job did not complete. Showing logs from all pods..."
            for pod in $(kubectl get pods -n default -l job-name=simplecrud-migrate -o jsonpath='{.items[*].metadata.name}'); do
              echo "🔹 Logs from pod: $pod"
              kubectl logs -n default $pod || true
              echo "--------------------------------------"
            done
            exit 1
          fi
          echo "✅ Migration job completed successfully."

          echo "🧹 Cleaning up migration job..."
          kubectl delete job simplecrud-migrate -n default --ignore-not-found

      - name: Deploy App (Deployment + Service + Ingress)
        run: kubectl apply -f k8s/simplecrud.yaml
        # Деплой приложения (Deployment, Service и Ingress для доступа снаружи)

      - name: Wait for app rollout
        run: kubectl rollout status deployment/simplecrud -n default --timeout=180s
        # Ждём пока деплоймент завершится

      - name: Wait for TLS certificate
        run: |                             # Ждём выпуск TLS сертификата Let's Encrypt
          echo "⏳ Waiting for TLS certificate simplecrud-tls..."
          kubectl wait --for=condition=Ready certificate/simplecrud-tls -n default --timeout=300s || \
            (echo "❌ TLS certificate was not issued" && kubectl describe certificate/simplecrud-tls -n default && exit 1)

      - name: Debug simplecrud pods if rollout fails
        if: failure()                      # Если деплой упал — выводим логи Pod'ов
        run: |
          kubectl get pods -n default
          for pod in $(kubectl get pods -n default -l app=simplecrud -o jsonpath='{.items[*].metadata.name}'); do
            echo "Logs from $pod"
            kubectl logs -n default $pod --tail=50 || true
            echo "---"
          done

      - name: Wait for Ingress to be ready
        run: |                             # Делаем несколько попыток curl к Ingress
          echo "⏳ Waiting for Ingress endpoint..."
          for i in {1..30}; do
            if curl -sk https://simplecrud.compnet.kz/health | grep '"status":"ok"'; then
              echo "✅ API is healthy"
              exit 0
            fi
            echo "Retry $i: not ready yet..."
            sleep 10
          done
          echo "❌ API did not become ready in time"
          exit 1

      - name: Show Ingress and endpoints
        run: |                             # Отладка: показываем ingress, сервисы и pod'ы
          kubectl get ingress -n default
          kubectl get svc -n default
          kubectl get pods -o wide -n default
